SELECT
	WO.ID WORK_ORDER_ID,
	WO.CODE WORK_ORDER_CODE,
    CASE
        WHEN WO.STATUS = 1 THEN 'Open'
        WHEN WO.STATUS =  0 THEN 'Closed'
        WHEN WO.STATUS = 5 THEN 'Registration in progress'
    END WO_STATUS,
    GA_TYPE_WORK_ORDER.DESCRIPTION WORK_ORDER_TYPE,
	UN_PROD.NAME PRODUCTION_UNIT,
	PROJ.DESCRIPTION PROJECT,
	PERI.DESCRIPTION PERIOD,
	TEAM.DESCRIPTION TEAM,
	WE.ID ENTRY_ID,
	WE.CODE ENTRY_CODE,
	TRUNC( WE.CLOSING_DATE ) ENTRY_DATE,
	OPER.DESCRIPTION OPERATION,
	LAY1.DESCRIPTION REGION,	
	LAY2.DESCRIPTION FARM,
	LAY3.DESCRIPTION BLOCK,
	LAY4.DESCRIPTION PADDOCK,
	VIEW_WO.AREA_CELL_LANC ENTRY_AREA
FROM 
	GATEC_SIMPLEFARM.GA_MVIEW_COMPLETE_WORK_ORDER VIEW_WO
	INNER JOIN GATEC_SIMPLEFARM.GA_AGR_WORK_ORDER WO 
        ON WO.ID = VIEW_WO.ID -- AND WO.TYPE_WORK_ORDER_ID = 3 
    INNER JOIN GATEC_SIMPLEFARM.GA_TYPE_WORK_ORDER 
        ON GA_TYPE_WORK_ORDER.ID = WO.TYPE_WORK_ORDER_ID
    INNER JOIN GATEC_SIMPLEFARM.GA_TYPE_WORK_ORDER WOTY 
        ON WOTY.ID = WO.TYPE_WORK_ORDER_ID
	INNER JOIN GATEC_SIMPLEFARM.GA_AGR_WORK_ORDER_ENTRY WE 
        ON WE.ID = VIEW_WO.ID_LANC -- AND WE.STATUS = 2 -- closed entries
	INNER JOIN GATEC_SIMPLEFARM.GA_TEAM TEAM 
        ON TEAM.ID = WO.TEAM_ID
	INNER JOIN GATEC_SIMPLEFARM.GA_PROCESS PROC 
        ON PROC.ID = VIEW_WO.ID_OPERACAO_LANC
	INNER JOIN GATEC_SIMPLEFARM.GA_OPERATION OPER 
        ON OPER.ID = PROC.OPERATION_ID 
	INNER JOIN GATEC_SIMPLEFARM.GA_CELL_AGR C_AGR 
        ON C_AGR.ID = VIEW_WO.ID_CELL_LANC -- paddock basic information
	INNER JOIN GATEC_SIMPLEFARM.GA_CELL CELL 
        ON CELL.ID = C_AGR.ID -- connecting paddock with layer
	INNER JOIN GATEC_SIMPLEFARM.GA_LAYERS LAY4
        ON LAY4.ID = CELL.LAYER_ID
	INNER JOIN GATEC_SIMPLEFARM.GA_LAYERS LAY3
        ON LAY3.ID = LAY4.PARENT_ID 
	INNER JOIN GATEC_SIMPLEFARM.GA_LAYERS LAY2
        ON LAY2.ID = LAY3.PARENT_ID
	INNER JOIN GATEC_SIMPLEFARM.GA_LAYERS LAY1 
        ON LAY1.ID = LAY2.PARENT_ID
	INNER JOIN GATEC_SIMPLEFARM.GA_PRODUCTION_UNIT UN_PROD
        ON UN_PROD.ID = WO.PRODUCTION_UNIT_ID
	INNER JOIN GATEC_SIMPLEFARM.GA_PROJECT PROJ
        ON PROJ.ID = WO.PROJECT_ID 
	INNER JOIN GATEC_SIMPLEFARM.GA_PERIOD PERI
        ON PERI.ID = WO.PERIOD_ID
	INNER JOIN GATEC_SIMPLEFARM.GA_CELL_AGR_AREA C_AREA
        ON C_AREA.CELL_ID = C_AGR.ID 
        AND C_AREA.PROJECT_ID = PROJ.ID
	LEFT JOIN GATEC_SIMPLEFARM.GA_CELL_AGR_CULTURE C_CULT 
        ON C_CULT.CELL_AGR_AREA_ID = C_AREA.ID -- paddock's crops
    	AND C_CULT.PERIOD_ID = PERI.ID
		AND C_CULT.CULTURE_ID = WO.CULTURE_ID											 
	LEFT JOIN GATEC_SIMPLEFARM.GA_CULTURE_STAGE C_STAGE 
        ON C_STAGE.ID = C_CULT.CULTURE_STAGE_ID	

-- WHERE
	-- ( C_CULT.PLANT = 1 OR C_STAGE.HARVEST_NUMBER = 1 ) -- Apenas plantio ou primeira colheita
	-- AND (PROJ.DESCRIPTION IN ([PROJETO]) OR ('-1') IN ([PROJETO]))	
	-- AND (PERI.DESCRIPTION IN ([PERIODO]) OR ('-1') IN ([PERIODO]))
	-- AND (UN_PROD.CODE || ' - ' || UN_PROD.NAME IN ([UNID_PRODUTORA]) OR ('-1') IN ([UNID_PRODUTORA]))