SELECT
    WO.CODE AS WO_CODE,
    WOE.CODE AS ENTRY_CODE,
    WOE.EXECUTION_DATE AS EXECUTION_DATE,
    PP.PLANNED_AREA,
    NVL(R.REALIZED_AREA,0) AS REALIZED_AREA,
    PROJ.DESCRIPTION AS PROJECT,
    PERI.DESCRIPTION AS PERIOD,
    CULT.DESCRIPTION AS CULTURE,
    WO.OPENING_DATE AS WO_OPEN_DATE,
    WO.CLOSING_DATE AS WO_CLOSE_DATE,
    LAY2.DESCRIPTION AS FARM,
    LAY3.DESCRIPTION AS BLOCK,
    LAY4.DESCRIPTION AS PADDOCK,
    WOTY.DESCRIPTION AS WO_TYPE,
    OPER.CODE AS OPERATION_CODE,
    OPER.DESCRIPTION AS OPERATION,
    GRUP.CODE AS OPERATION_GROUP_CODE,
    GRUP.DESCRIPTION AS OPERATION_GROUP,
    SUBP.CODE AS SUBPROCESS_CODE,
    SUBP.DESCRIPTION AS SUBPROCESS,
    V.VARIETY,
    CASE WO.STATUS
        WHEN 0 THEN 'Closed'
        WHEN 1 THEN 'Open'
        WHEN 2 THEN 'Pending'
        WHEN 3 THEN 'Canceled'
        WHEN 4 THEN 'Pending Approval'
        WHEN 5 THEN 'Registration In Progress'
    END AS WO_STATUS,
    ROUND(
        (NVL(R.REALIZED_AREA,0) / NULLIF(PP.PLANNED_AREA,0)) * 100,
        2
    ) AS COMP,
    UNP.NAME AS COMPANY
FROM GATEC_SIMPLEFARM.GA_AGR_WORK_ORDER WO
INNER JOIN GATEC_SIMPLEFARM.GA_AGR_WORK_ORDER_ENTRY WOE
    ON WOE.WORK_ORDER_ID = WO.ID
INNER JOIN (
    SELECT DISTINCT
        VIEW_WO.ID AS WORK_ORDER_ID,
        VIEW_WO.ID_CELL_OS AS CELL_ID,
        VIEW_WO.AREA_CELL_OS AS PLANNED_AREA
    FROM GATEC_SIMPLEFARM.GA_MVIEW_COMPLETE_WORK_ORDER VIEW_WO
    WHERE VIEW_WO.ID_CELL_OS IS NOT NULL
) PP
    ON PP.WORK_ORDER_ID = WO.ID
LEFT JOIN (
    SELECT
        WOE.ID AS ENTRY_ID,
        WOCE.CELL_AGR_ID AS CELL_ID,
        SUM(WOCE.TOTAL_AREA) AS REALIZED_AREA
    FROM GATEC_SIMPLEFARM.GA_AGR_WORK_ORDER_ENTRY WOE
    INNER JOIN GATEC_SIMPLEFARM.GA_AGR_WORK_ORDER_CELL_ENTRY WOCE
        ON WOCE.WORK_ORDER_ENTRY_ID = WOE.ID
    GROUP BY
        WOE.ID,
        WOCE.CELL_AGR_ID
) R
    ON R.ENTRY_ID = WOE.ID
   AND R.CELL_ID = PP.CELL_ID
LEFT JOIN (
    SELECT
        WOE.ID AS ENTRY_ID,
        WOCE.CELL_AGR_ID AS CELL_ID,
        LISTAGG(DISTINCT VARI.DESCRIPTION, ', ')
            WITHIN GROUP (ORDER BY VARI.DESCRIPTION) AS VARIETY
    FROM GATEC_SIMPLEFARM.GA_AGR_WORK_ORDER_ENTRY WOE
    INNER JOIN GATEC_SIMPLEFARM.GA_AGR_WORK_ORDER_CELL_ENTRY WOCE
        ON WOCE.WORK_ORDER_ENTRY_ID = WOE.ID
    INNER JOIN GATEC_SIMPLEFARM.GA_AGR_WORK_ORDER_PLANT_ENTRY WOP
        ON WOP.WORK_ORDER_CELL_ENTRY_ID = WOCE.ID
    INNER JOIN GATEC_SIMPLEFARM.GA_VARIETY VARI
        ON VARI.ID = WOP.VARIETY_ID
    GROUP BY
        WOE.ID,
        WOCE.CELL_AGR_ID
) V
    ON V.ENTRY_ID = WOE.ID
   AND V.CELL_ID = PP.CELL_ID
LEFT JOIN (
    SELECT DISTINCT
        VIEW_WO.ID AS WORK_ORDER_ID,
        VIEW_WO.ID_CELL_OS AS CELL_ID,
        VIEW_WO.ID_OPERACAO_OS AS OPERATION_ID
    FROM GATEC_SIMPLEFARM.GA_MVIEW_COMPLETE_WORK_ORDER VIEW_WO
    WHERE VIEW_WO.ID_CELL_OS IS NOT NULL
      AND VIEW_WO.ID_OPERACAO_OS IS NOT NULL
) OP
    ON OP.WORK_ORDER_ID = WO.ID
   AND OP.CELL_ID = PP.CELL_ID
INNER JOIN GATEC_SIMPLEFARM.GA_CELL_AGR C_AGR
    ON C_AGR.ID = PP.CELL_ID
INNER JOIN GATEC_SIMPLEFARM.GA_CELL CELL
    ON CELL.ID = C_AGR.ID
INNER JOIN GATEC_SIMPLEFARM.GA_LAYERS LAY4
    ON LAY4.ID = CELL.LAYER_ID
INNER JOIN GATEC_SIMPLEFARM.GA_LAYERS LAY3
    ON LAY3.ID = LAY4.PARENT_ID
INNER JOIN GATEC_SIMPLEFARM.GA_LAYERS LAY2
    ON LAY2.ID = LAY3.PARENT_ID
LEFT JOIN GATEC_SIMPLEFARM.GA_PROCESS OPER
    ON OPER.ID = OP.OPERATION_ID
LEFT JOIN GATEC_SIMPLEFARM.GA_PROCESS GRUP
    ON GRUP.ID = OPER.PARENT_ID
LEFT JOIN GATEC_SIMPLEFARM.GA_PROCESS SUBP
    ON SUBP.ID = GRUP.PARENT_ID
INNER JOIN GATEC_SIMPLEFARM.GA_TYPE_WORK_ORDER WOTY
    ON WOTY.ID = WO.TYPE_WORK_ORDER_ID
INNER JOIN GATEC_SIMPLEFARM.GA_PRODUCTION_UNIT UNP
    ON UNP.ID = WO.PRODUCTION_UNIT_ID
INNER JOIN GATEC_SIMPLEFARM.GA_PROJECT PROJ
    ON PROJ.ID = WO.PROJECT_ID
INNER JOIN GATEC_SIMPLEFARM.GA_PERIOD PERI
    ON PERI.ID = WO.PERIOD_ID
LEFT JOIN GATEC_SIMPLEFARM.GA_CULTURE CULT
    ON CULT.ID = WO.CULTURE_ID
